# Generated by Django 2.0.2 on 2018-07-14 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fg_competitions', '0016_merge_20180629_1412'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=8, max_digits=19)),
                ('time_taken', models.PositiveIntegerField(default=0)),
                ('outcome', models.CharField(choices=[('L', 'Loss'), ('D', 'Draw'), ('W', 'Win'), ('X', 'Disqualified')], max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='fg_scoreboards.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fg_competitions.Submission')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fg_scoreboards.ScoreBoard'),
        ),
        migrations.AddField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
