image: python:3.4-alpine

before_script:
    - pip install -r requirements.txt

stages:
    - validate
    - test

check:
    stage: validate
    script:
        - python manage.py check
    except:
        - tags

migrate:
    stage: validate
    script:
        - python manage.py migrate
    except:
        - tags

django_test:
    stage: test
    script:
        - python manage.py test
    except:
        - tags
