image: python:3.4-alpine

before_script:
    - pip install -r requirements.txt

stages:
    - validate
    - test
    - deploy

check:
    stage: validate
    script:
        - python manage.py check
    except:
        - tags

migrate:
    stage: validate
    script:
        - python manage.py migrate
    except:
        - tags

django_test:
    stage: test
    script:
        - python manage.py test
    except:
        - tags

dist:
    stage: deploy
    tags:
        - shell
    before_script:
        - echo deploying to docker hub
    script:
        - "docker build -t fossgalaxy/comet ."
        - "docker push fossgalaxy/comet"
