# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('summary', models.CharField(max_length=250)),
                ('body', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
