# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fg_competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionlink',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='fg_competitions.Competition'),
        ),
    ]
