# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fg_competitions', '0005_track_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='sample',
            field=models.BooleanField(default=False),
        ),
    ]
