# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-18 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fg_competitions', '0006_submission_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('BP', 'Build pending'), ('BF', 'Build failed'), ('BS', 'Build succeeded'), ('DA', 'Disqualified by admin')], default='BP', max_length=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('body', models.TextField(null=True)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-ranking', 'ranking_rd']},
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_type',
            field=models.CharField(choices=[('T', 'Text Submission'), ('U', 'Upload')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='submissiontext',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_submissions', to='fg_competitions.Submission'),
        ),
    ]
