# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-08 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fg_competitions', '0007_auto_20180208_1628'),
        ('fg_competitions', '0008_auto_20170912_1829'),
    ]

    operations = [
    ]
