# Generated by Django 2.0.2 on 2018-03-08 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fg_competitions', '0009_merge_20180208_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='allow_download',
            field=models.BooleanField(default=False),
        ),
    ]
