# Generated by Django 2.0.2 on 2018-03-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fg_competitions', '0011_auto_20180309_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_student',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='n', help_text='Is this submission by a student?', max_length=1, verbose_name='Student Submission'),
            preserve_default=False,
        ),
    ]
