# Generated by Django 2.0.2 on 2018-03-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fg_competitions', '0012_submission_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='allow_download',
            field=models.BooleanField(default=True, help_text='Allow public distribution after results publication', verbose_name='Make public'),
        ),
    ]
