# Generated by Django 2.0.2 on 2018-06-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fg_competitions', '0013_auto_20180312_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissiontext',
            name='status',
            field=models.CharField(choices=[('BP', 'Build pending'), ('BF', 'Build failed'), ('VP', 'Validation Pending'), ('VF', 'Validation Failed'), ('BS', 'Build succeeded'), ('VS', 'Validation succeeded'), ('DA', 'Disqualified by admin')], default='BP', max_length=5),
        ),
        migrations.AlterField(
            model_name='submissionupload',
            name='status',
            field=models.CharField(choices=[('BP', 'Build pending'), ('BF', 'Build failed'), ('VP', 'Validation Pending'), ('VF', 'Validation Failed'), ('BS', 'Build succeeded'), ('VS', 'Validation succeeded'), ('DA', 'Disqualified by admin')], default='BP', max_length=5),
        ),
    ]
