# Generated by Django 2.0.2 on 2018-06-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fg_competitions', '0014_auto_20180626_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-allow_submit', 'name']},
        ),
    ]
