# Generated by Django 2.0.2 on 2018-06-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fg_competitions', '0014_auto_20180628_2139'),
        ('fg_competitions', '0015_auto_20180628_1457'),
    ]

    operations = [
    ]
