# Generated by Django 2.1.7 on 2019-03-19 11:48

from django.db import migrations, models
import django.db.models.deletion
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('fg_competitions', '0016_merge_20180629_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('body', martor.models.MartorField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='track',
            name='allow_submit',
            field=models.BooleanField(default=True, help_text='Can new submissions be added'),
        ),
        migrations.AlterField(
            model_name='track',
            name='allow_update',
            field=models.BooleanField(default=True, help_text='Can existing submissions be updated'),
        ),
        migrations.AddField(
            model_name='trackpage',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fg_competitions.Track'),
        ),
    ]
